const overlook = ["im xalen"]

function Corrector(text) {
    let result = text;

    // 
    result = result.replace("are not", "arent");
    result = result.replace("how are", "howre")
    result = result.replace("you are", "youre")
    result = result.replace("i am", "im")
    result = result.replace("we are", "were")
    result = result.replace("is not", "isnt")
    result = result.replace(" is ", "s ")
    result = result.replace("they are", "theyre")
    result = result.replace("i have", "ive")
    result = result.replace("you have", "youve")
    result = result.replace("have not", "havent")
    result = result.replace("cannot", "cant")
    result = result.replace("can not", "cant")
    result = result.replace("will not", "wont")
    result = result.replace("should not", "shouldnt")
    result = result.replace("would not", "wouldnt")
    result = result.replace("does not", "doesnt")
    result = result.replace("do not", "dont")
    result = result.replace("did not", "didnt")
    result = result.replace("could not", "couldnt")
    result = result.replace(" had ", "d ")
    result = result.replace("he will", "hell")
    result = result.replace("she will", "shell")
    result = result.replace(" will ", "ll ")

    // Abbreviations
    result = result.replace("were not", "werent")
    result = result.replace("want to", "wanna")
    result = result.replace("going to", "gonna")
    result = result.replace("dont know", "dunno")
    result = result.replace("give me", "gimme")
    result = result.replace("leave me", "lemme")
    result = result.replace("dont know", "dunno")
    result = result.replace("what do you", "whatcha")

    // British/American
    result = result.replace(/w*our\b/, "or")
    result = result.replace(/w*ize\b/, "ise")
    result = result.replace(/w*yze\b/, "yse")
    result = result.replace(/w*ogue\b/, "og")
    result = result.replace(/w*ae\b/, "e")
    result = result.replace(/w*oe\b/, "e")
    result = result.replace("favorite", "favourite")
    result = result.replace("traveled", "travelled")
    result = result.replace("traveling", "travelling")
    result = result.replace("traveler", "traveller")
    result = result.replace("maneuver", "manoeuvre")
    result = result.replace("defense", "defence")
    result = result.replace("license", "licence")
    result = result.replace("offense", "offence")
    result = result.replace("pretense", "pretence")
    result = result.replace("gray", "grey")
    result = result.replace("whisky", "whiskey")
    result = result.replace("phial", "vial")
    result = result.replace("sceptic", "skeptic")
    result = result.replace("pygamas", "pajamas")
    result = result.replace("nought", "naught")
    result = result.replace("moustache", "mustache")
    result = result.replace("liquorice", "licorice")
    result = result.replace("carat", "karat")
    result = result.replace("furore", "furor")
    result = result.replace("kerb", "curb")
    result = result.replace("cosy", "cozy")
    result = result.replace("axe", "ax")
    result = result.replace("aluminium", "aluminum")
    result = result.replace("acknowlodgement", "acknowledgment")
    result = result.replace("ageing", "aging")
    result = result.replace("judgement", "judgment")
    result = result.replace("cheque", "check")
    result = result.replace("chequer", "check")
    result = result.replace("programme", "program")
    result = result.replace("tyre", "tire")
    result = result.replace("mould", "mold")
    result = result.replace("smoulder", "smolder")
    result = result.replace("draught", "draft")
    result = result.replace("plough", "plow")
    result = result.replace("sulphur", "sulfur")
    result = result.replace("vice", "vise")
    result = result.replace("practise", "practice")
    result = result.replace("wilful", "willful")
    result = result.replace("skilful", "skillful")
    result = result.replace("instil", "instill")
    result = result.replace("fulfil", "fulfill")
    result = result.replace("enthral", "enthrall")
    result = result.replace("enrol", "enroll")
    result = result.replace("distil", "distill")
    result = result.replace("cancelled", "canceled")
    result = result.replace("counsellor", "counselor")
    result = result.replace("marvellous", "marvelous")
    result = result.replace("jewellery", "jewelery")
    result = result.replace("grovelling", "groveling")
    result = result.replace("libelled", "libeled")
    result = result.replace("quarrelling", "quarreling")
    result = result.replace("woollen", "woolen")
    result = result.replace("appal", "appall")
    result = result.replace("levelled", "leveled")
    result = result.replace("fuelling", "fueling")

    // Nicknames
    result = result.replace("dad", "father")
    result = result.replace("mom", "mother")
    result = result.replace("daddy", "father")
    result = result.replace("mommy", "mother")
    result = result.replace("mum", "mother")
    result = result.replace("brother", "bro")
    result = result.replace("sister", "sis")

    // Adverbs
    result = result.replace(" actually ", " ")
    result = result.replace(" really ", " ")
    result = result.replace(" usually ", " ")
    result = result.replace(" totally ", " ")
    result = result.replace(" so ", " ")
    result = result.replace(" kind of ", " ")
    result = result.replace(" just ", " ")
    result = result.replace(" literally ", " ")
    result = result.replace(" simply ", " ")
    result = result.replace(" absolutely ", " ")
    result = result.replace(" completely ", " ")
    result = result.replace(" sort of ", " ")
    result = result.replace(" almost ", " ")
    result = result.replace(" clearly ", " ")
    result = result.replace(" easily ", " ")
    result = result.replace(" even ", " ")
    result = result.replace(" exactly ", " ")
    result = result.replace(" frankly ", " ")
    result = result.replace(" immediately ", " ")
    result = result.replace(" innocently ", " ")
    result = result.replace(" instantly ", " ")
    result = result.replace(" mostly ", " ")
    result = result.replace(" nearly ", " ")
    result = result.replace(" nicely ", " ")
    result = result.replace(" officially ", " ")
    result = result.replace(" obediently ", " ")
    result = result.replace(" often ", " ")
    result = result.replace(" patiently ", " ")
    result = result.replace(" quickly ", " ")
    result = result.replace(" properly ", " ")
    result = result.replace(" rarely ", " ")
    result = result.replace(" soon ", " ")
    result = result.replace(" unnecessarily ", " ")
    result = result.replace(" virtually ", " ")
    result = result.replace(" practically ", " ")
    result = result.replace(" already ", " ")
    result = result.replace(" still ", " ")
    result = result.replace(" basically ", " ")
    result = result.replace("", "")
    result = result.replace("", "")
    result = result.replace("", "")
    result = result.replace("", "")
    result = result.replace("", "")
    result = result.replace("", "")
    result = result.replace("", "")
    result = result.replace("", "")
    result = result.replace("", "")
    result = result.replace("", "")
    result = result.replace("", "")
    result = result.replace("", "")
    result = result.replace("", "")
    result = result.replace("", "")
    result = result.replace("", "")
    result = result.replace("", "")

    result = result.replace(/w* xalen\b/, "");

    if (result.trim().length < 4) result = text;

    return result
}

module.exports = Corrector;