const Tree = [
    {
        alpha: null,
        beta: null,
        gamma: null,
        delta: null,
        epilson: null,
        zeta: null,
        eta: null,
        theta: null,
        iota: null,
        kappa: null,
        omega: "Hello!"
    },
    {
        alpha: null,
        beta: null,
        gamma: null,
        delta: null,
        epilson: null,
        zeta: null,
        eta: null,
        theta: null,
        iota: null,
        kappa: null,
        omega: "Hi!"
    },
    {
        alpha: null,
        beta: null,
        gamma: null,
        delta: null,
        epilson: null,
        zeta: null,
        eta: null,
        theta: null,
        iota: null,
        kappa: null,
        omega: "Hola!"
    },
    {
        alpha: null,
        beta: null,
        gamma: null,
        delta: null,
        epilson: null,
        zeta: null,
        eta: null,
        theta: null,
        iota: null,
        kappa: null,
        omega: "Konnichiwa!"
    },
    {
        alpha: null,
        beta: null,
        gamma: null,
        delta: null,
        epilson: null,
        zeta: null,
        eta: null,
        theta: null,
        iota: null,
        kappa: null,
        omega: "Howdy! How do you do?"
    },
    {
        alpha: null,
        beta: null,
        gamma: null,
        delta: null,
        epilson: null,
        zeta: null,
        eta: null,
        theta: null,
        iota: null,
        kappa: null,
        omega: "Hiya!"
    },
    {
        alpha: null,
        beta: null,
        gamma: null,
        delta: null,
        epilson: null,
        zeta: null,
        eta: null,
        theta: null,
        iota: null,
        kappa: null,
        omega: "What's up?"
    },
    {
        alpha: null,
        beta: null,
        gamma: null,
        delta: null,
        epilson: null,
        zeta: null,
        eta: null,
        theta: null,
        iota: null,
        kappa: null,
        omega: "Sup?"
    },
    {
        alpha: null,
        beta: null,
        gamma: null,
        delta: null,
        epilson: null,
        zeta: null,
        eta: null,
        theta: null,
        iota: null,
        kappa: null,
        omega: "Wassup?"
    }
]

module.exports = Tree;