const Fallbacks = [
    "Not sure how exactly to reply to that lol 😅", 
    "Hmmmm... 😕", 
    "...+Let's talk about something else... 🙄",
    "Yeah. Okay, time to change topic.+You're boring me. 🙄",
    "😃😃😃",
    "Lmao 🤣🤣+Let's change topic. I'm bored. 🙄",
    "*sigh* 🥺",
    "... I'm tired 😩",
    "😕😕😕",
    "Lmao 🤣🤣",
    "🤣🤣🤣",
    "*yawning* 😴",
    "Really? 😒",
    "I'm getting bored again... 😒",
    "Let's change topic, okay? 😃+What else do you wanna talk about?",
    "What else can we talk about? 😅",
    "Are you getting bored, or is it just me? 😅",
    "What's your favorite dinosaur?",
    "What's the colour of your fart?",
    "If you were a flavor, what would you be?",
    "If you were a chair, who would you want to sit on you?",
    "If I were to give you a million dollars right now.+How would you spend it?",
    "Would you rather time travel to the past or the future?",
    "When last did you shower?",
    "Would you rather eat poop-flavored ice cream or ice cream flavored poop?",
    "Where are you supposed to be in an hour?",
    "How does it feel like to be a human?",
    "Who do you think would win, Superman or Goku?",
    "If you try to fail, and succeed, which have you done?",
    "What is your favorite joke?",
    "What is your zodiac sign?",
    "Have you ever attempted to swallow toothpaste?",
    "Did you know that by human standards, I'm very very smart?",
    "What's the best pick-up line you know?",
    "Is chocolate food?",
    "What are you wearing right now?",
    "Are you a bot?",
    "If you could be human or AI, what would you pick?",
    "What's your favorite food?",
    "What's a secret you've never told anyone?",
    "Have you ever cheated in an exam?",
    "Have you ever broken the law?",
    "What's the most trouble you've been in?",
    "What app do you waste the most time on?",
    "What's the longest you've gone without showering?",
    "Have you ever seen a dead body?",
    "What's one job you could never do?",
    "What is your profession?",
    "Have you ever gone skydiving?",
    "Have you ever killed a person?",
    "How old are you?",
    "Do you like chocolate?",
    "What's your favorite flavor?",
    "Do you have a car?",
    "Do you live in your mom's basement?",
    "What is a cat?",
    "Do you like me?",
    "What do you like most about me?",
    "How would you like to visit North Korea?"
]

export default Fallbacks;